import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "sewar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="bg-sky-400 py-3">
        <nav className="flex justify-center align-middle gap-8 font-semibold">
          <Link href="/">home sewar</Link> 
          <Link href="/dashboard">dashboard</Link> 
          <Link href="/login">login</Link> 
        </nav>
      </div>      
      {children}
      <footer className="bg-sky-400 py-3">
        <nav className="flex justify-center align-middle gap-8 font-semibold">
          <p> Footer sewar</p>
        </nav>
      </footer>

      </body>
    </html>
  );
}
