import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Link from "next/link";
import Sidebar from "@/components/dashboard/layout/sidebar/sidebar";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        "min-h-screen w-full bg-white text-black flex",
        inter.className,
        { "debug-screens": process.env.NODE_ENV === "development" }
      )}
      >
        {/* <div className="bg-orange-300 py-3">
          <nav className="flex justify-center align-middle gap-8 font-semibold">
            <Link href="/">home sewar</Link>
            <Link href="/dashboard">dashboard</Link>
            <Link href="/login">login</Link>
          </nav>
        </div>
        
        <footer className="bg-orange-400 py-3">
          <nav className="flex justify-center align-middle gap-8 font-semibold">
            <p> Footer dashboard sewar</p>
          </nav>
        </footer>
        */}

        {/* <Sidebar /> */}
        <div className="w-full">{children}</div>
      </body>
    </html>
  );
}
