import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Link from "next/link";
import Sidebar from "@/components/dashboard/layout/sidebar/test/sidebar";
import { cn } from "@/lib/utils";
import HomeDash from '@/components/dashboard/content/home/home';
import HomeHeaderDash from '@/components/dashboard/layout/header/header';
import Aside from '@/components/dashboard/layout/sidebar/aside';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        "min-h-screen w-full bg-white text-black flex",
        inter.className  )}
      >


    <div className="flex w-full flex-col bg-muted/40">
      <Aside />
      <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-52">
        <HomeHeaderDash />
        <main>
          {children}
        </main>
      </div>
    </div>

        
      </body>
    </html>
  );
}
