import { ReactNode } from 'react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import HomeHeaderDash from '@/components/dashboard/layout/header/header';
import Aside from '@/components/dashboard/layout/sidebar/aside';
import LocaleSwitcher from "@/components/LocaleSwitcher"
const inter = Inter({ subsets: ["latin"] });
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';


export const metadata: Metadata = {
  title: "dashboard",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

export default async function RootLayout({ children }: Props) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <body>

        <NextIntlClientProvider messages={messages}>

          {/* <div className="flex flex-col flex-grow" id="kt_app_root">
            <div className="flex flex-col flex-grow" id="kt_app_page">
              <div id="kt_app_header" className="bg-white shadow-sm">
                <div className="container mx-auto flex items-center justify-between p-4" id="kt_app_header_container">
                  <div className="lg:hidden flex items-center ms-[-12px] me-1 me-md-2" title="Show sidebar menu">
                    <button className="w-9 h-9 p-1 flex items-center justify-center text-primary" id="kt_app_sidebar_mobile_toggle">
                      <span className="w-6 h-6 flex items-center justify-center">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <path d="M21 7H3C2.4 7 2 6.6 2 6V4C2 3.4 2.4 3 3 3H21C21.6 3 22 3.4 22 4V6C22 6.6 21.6 7 21 7Z" fill="currentColor" />
                          <path opacity="0.3" d="M21 14H3C2.4 14 2 13.6 2 13V11C2 10.4 2.4 10 3 10H21C21.6 10 22 10.4 22 11V13C22 13.6 21.6 14 21 14ZM22 20V18C22 17.4 21.6 17 21 17H3C2.4 17 2 17.4 2 18V20C2 20.6 2.4 21 3 21H21C21.6 21 22 20.6 22 20Z" fill="currentColor" />
                        </svg>
                      </span>
                    </button>
                  </div>

                  <div className="flex items-center flex-grow-1 lg:flex-grow-0">
                    <a href="../../demo1/dist/index.html" className="lg:hidden">
                      <img alt="Logo" src="assets/media/logos/default-small.svg" className="h-8" />
                    </a>
                  </div>


                  <div className="flex items-stretch justify-between flex-grow">
                    <div className="flex items-stretch">
                      <div className="flex flex-col lg:flex-row my-5 lg:my-0 items-stretch font-semibold px-2 lg:px-0" id="kt_app_header_menu" data-kt-menu="true">
                        <div  className="flex items-center bg-gray-100 hover:bg-gray-200 rounded-lg me-0 lg:me-2 p-2">
                          <span className="flex items-center">
                            <span className="text-gray-800">Dashboards</span>
                            <span className="lg:hidden ml-2">▼</span>
                          </span>

                        </div>
                        <div className="flex items-center p-2 rounded-lg cursor-pointer">
                          <span className="flex items-center text-gray-800">Pages</span>
                        </div>
                      </div>
                    </div>
                  </div>


                </div>
              </div>
            </div>
          </div> */}

          

          <div className="flex">
              <aside className="fixed w-56 h-screen bg-gray-100">aside</aside>
              <div className="ms-56">
                <header className="fixed w-full bg-gray-100">
                  <nav className="flex items-center justify-between p-4">
                    <div className="flex items-center">
                    header
                    <LocaleSwitcher />
                    </div>
                  </nav>
                </header>
                <main>{children}{children}{children}{children}{children}{children}{children}</main>
              </div>
          </div>

        </NextIntlClientProvider>


        {/* <div className="flex w-full flex-col bg-muted">
          <Aside />
          <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-52">
            <HomeHeaderDash />
            <LocaleSwitcher />
            <NextIntlClientProvider messages={messages}>
              <main className="">
                {children}
              </main>
            </NextIntlClientProvider>

          </div>
        </div> */}






      </body>
    </html>
  )
}
